[window.padding]
x = 10
y = 5

[colors.primary]
background = '#1d2021'
foreground = '#ffffff'

[colors.normal]
black   = '#303536'
red     = '#ea6962'
green   = '#a9b665'
yellow  = '#d8a657'
blue    = '#7daea3'
magenta = '#d3869b'
cyan    = '#89b482'
white   = '#ffffff'

[colors.bright]
black   = '#434a4c'
red     = '#ee8b86'
green   = '#b7c37f'
yellow  = '#dfb777'
blue    = '#97beb6'
magenta = '#dfa5b4'
cyan    = '#a1c49c'
white   = '#ebe1d0'

[font]
size = 8.25
